import re
from langchain.prompts.chat import ChatPromptTemplate
from langchain_core.runnables import RunnablePassthrough, RunnableParallel
from src.utils.llmutils import (
    get_gemini_llm,
    get_claude_llm,
)
from src.chains.PlotColumnsChain import get_plot_columns_chain
from src.utils.constants import FAILURE_RESPONSE
from src.utils.bigqueryutils import get_database
from langchain.output_parsers.structured import ResponseSchema, StructuredOutputParser
from langchain.prompts import ChatPromptTemplate


def get_nlp_response_chain(db=get_database()):
    llm = get_claude_llm()

    with open("src/prompts/nlresponse_prompt.txt") as f:
        template = f.read()

    prompt = ChatPromptTemplate.from_template(template)

    nlp_response_schema = ResponseSchema(
        name="nlp_output",
        description="This is the natural language response generated by the LLM based on the Conversation History, SQL Query, User question and SQL response. DO NOT include any links here in the response.",
    )

    nlp_output_parser = StructuredOutputParser(response_schemas=[nlp_response_schema])

    nlp_output_generation_chain = RunnablePassthrough.assign(
        response=lambda vars: db.run(vars["query"])
    ).assign(output=prompt | llm | nlp_output_parser)

    return nlp_output_generation_chain, nlp_output_parser


def contains_plot_information(query):
    # Define keywords and patterns related to plot and chart requests
    chart_keywords = [
        "chart",
        "graph",
        "visualization",
        "plot",
        "bar chart",
        "pie chart",
        "line chart",
        "scatter plot",
        "histogram",
        "data",
        "trend",
        "comparison",
        "distribution",
        "show me",
        "generate",
        "create",
        "display",
        "highlight",
        "center the title",
        "x-axis",
        "y-axis",
        "filter",
        "interact",
        "detailed view",
        "units",
        "overview",
        "summary",
        "data points",
        "plotly",
        "matplotlib",
        "seaborn",
        "plot type",
        "chart type",
        "axis labels",
        "legend",
        "markers",
        "tooltip",
        "bar graph",
        "area chart",
        "bubble chart",
        "heatmap",
        "stacked chart",
        "percentage",
        "ratio",
        "spread",
        "plot visualization",
        "data visualization",
        "present data",
        "visual representation",
        "graphical representation",
    ]

    # Convert the query to lower case for case-insensitive matching
    query_lower = query.lower()

    # Check for presence of chart-related keywords
    for keyword in chart_keywords:
        if re.search(r"\b" + re.escape(keyword) + r"\b", query_lower):
            return True

    return False


# Parallel execution of nlp response chain and plot columns chain
def get_nlp_response_and_plot_columns(
    user_query, sql_query, chat_history, sql_response, db=get_database()
):

    nlp_output_generation_chain, nlp_output_parser = get_nlp_response_chain(db=db)
    (
        plot_columns_chain,
        plot_columns_format_instructions,
        plot_columns_output_parser,
    ) = get_plot_columns_chain(user_query, sql_response)

    parallel_chain = RunnableParallel(
        nlp_response_chain=nlp_output_generation_chain,
        plot_columns_response_chain=plot_columns_chain,
    )

    parallel_chain_response = parallel_chain.invoke(
        {
            "input": user_query,
            "chat_history": chat_history,
            "query": sql_query,
            "nlp_format_instructions": nlp_output_parser.get_format_instructions(),
            "sql_response": sql_response,
            "plot_columns_format_instructions": plot_columns_format_instructions,
        }
    )

    # getting nlp response
    nlp_output = parallel_chain_response["nlp_response_chain"]["output"]
    result = {}
    result["nlp_output"] = nlp_output["nlp_output"]

    if len(sql_response) > 1:
        result["sql_response"] = sql_response
    else:
        result["sql_response"] = "N/A"
    print(f"Final response: \n\n {result}\n\n")

    # getting plot columns
    plot_columns = plot_columns_output_parser.parse(
        parallel_chain_response["plot_columns_response_chain"][
            "plot_columns_query"
        ].content
    )["plot_columns"]
    print(f"columns that can be used for plotting is {plot_columns}")
    if isinstance(plot_columns, str):
        plot_columns = plot_columns.split(",")
    plot_columns = [item.strip() for item in plot_columns]

    result["plot_columns"] = plot_columns
    return result, sql_query


def get_nlp_response_gen_exception(e):
    print(f"exception at getting nlp response {e}")
    sql_query = f"exception at getting nlp response {e}"
    result = {}
    result["nlp_output"] = FAILURE_RESPONSE
    result["sql_response"] = "N/A"
    return result, sql_query


def get_nlp_model_response_chain(db=get_database()):
    llm = get_claude_llm()

    with open("src/prompts/nlresponseMLmodel_prompt.txt") as f:
        template = f.read()

    prompt = ChatPromptTemplate.from_template(template)

    nlp_response_schema = ResponseSchema(
        name="nlp_output",
        description="This is the natural language response generated by the LLM based on the Conversation History, User question and Model Result. DO NOT include any links here in the response.",
    )

    nlp_output_parser = StructuredOutputParser(response_schemas=[nlp_response_schema])

    nlp_output_generation_chain = RunnablePassthrough.assign(
        output=prompt | llm | nlp_output_parser
    )

    return nlp_output_generation_chain, nlp_output_parser


def get_nlp_model_response(user_query, model_results, chat_history, db=get_database()):

    nlp_output_generation_chain, nlp_output_parser = get_nlp_model_response_chain(db=db)
    nlp_response = nlp_output_generation_chain.invoke(
        {
            "input": user_query,
            "chat_history": chat_history,
            "response": model_results,
            "nlp_format_instructions": nlp_output_parser.get_format_instructions(),
        }
    )
    nlp_output = nlp_response["output"]
    result = {}
    result["nlp_output"] = nlp_output["nlp_output"]
    result["sql_response"] = "N/A"
    return result, user_query
